#!/usr/bin/env bash
# fix-zebra-edams.sh
# Purpose: Restore EDAMS Zebra peripheral symlink on Amazon AFT-X thin clients.
# Root cause addressed:
#   - usblp module loaded but not bound to Zebra after USB reconnect cycles
#   - missing /dev/edams/peripheral_<serial> symlink that PrintServer Lambda writes to
#   - USB autosuspend dropping the device while idle
# Idempotent. Safe to run on any TC. Requires root.

set -euo pipefail

ZEBRA_VID="0a5f"
LOG_TAG="fix-zebra-edams"
UDEV_AUTOSUSPEND_RULE="/etc/udev/rules.d/98-zebra-no-autosuspend.rules"
USBLP_LOAD_CONF="/etc/modules-load.d/usblp.conf"

log() { echo "[${LOG_TAG}] $*"; }
die() { echo "[${LOG_TAG}] ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root."

# 1. Verify Zebra is physically connected
ZEBRA_PORT=""
for d in /sys/bus/usb/devices/*/; do
    [ -f "${d}idVendor" ] || continue
    if [ "$(cat "${d}idVendor")" = "${ZEBRA_VID}" ]; then
        ZEBRA_PORT="$(basename "${d}")"
        break
    fi
done
[ -n "${ZEBRA_PORT}" ] || die "No Zebra printer found on USB bus."
log "Zebra detected on port ${ZEBRA_PORT}"

# 2. Remove blacklist on usblp if present (preventive)
for f in /etc/modprobe.d/*.conf; do
    [ -f "${f}" ] && sed -i '/^blacklist[[:space:]]\+usblp/d' "${f}" || true
done

# 3. Ensure usblp loads at boot
if [ ! -f "${USBLP_LOAD_CONF}" ] || ! grep -q '^usblp' "${USBLP_LOAD_CONF}" 2>/dev/null; then
    echo "usblp" > "${USBLP_LOAD_CONF}"
    log "Configured usblp to load at boot"
fi

# 4. Force rebind of usblp (the actual fix that creates /dev/usb/lpN)
log "Reloading usblp module"
modprobe -r usblp 2>/dev/null || true
modprobe usblp
sleep 1

# 5. Disable USB autosuspend for any Zebra printer (preventive, by VID)
cat > "${UDEV_AUTOSUSPEND_RULE}" <<EOF
# Disable USB autosuspend for Zebra printers to prevent idle disconnects.
# Generated by fix-zebra-edams.sh
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="${ZEBRA_VID}", ATTR{power/control}="on"
EOF
log "Installed udev autosuspend rule: ${UDEV_AUTOSUSPEND_RULE}"

# 6. Reload udev and trigger
udevadm control --reload-rules
udevadm trigger --subsystem-match=usb --attr-match=idVendor="${ZEBRA_VID}" || true
sleep 1

# 7. Verify outcome
LP_NODE="$(ls -1 /dev/usb/lp* 2>/dev/null | head -1 || true)"
EDAMS_LINK="$(ls -1 /dev/edams/peripheral_* 2>/dev/null | head -1 || true)"

if [ -z "${LP_NODE}" ]; then
    log "usblp did not create /dev/usb/lpN. Attempting manual bind."
    if [ -e "/sys/bus/usb/devices/${ZEBRA_PORT}/${ZEBRA_PORT}:1.0" ]; then
        echo "${ZEBRA_PORT}:1.0" > /sys/bus/usb/drivers/usblp/bind 2>/dev/null || true
        sleep 1
        LP_NODE="$(ls -1 /dev/usb/lp* 2>/dev/null | head -1 || true)"
    fi
fi

[ -n "${LP_NODE}" ] || die "Failed to create /dev/usb/lpN. Check 'dmesg | tail' for kernel errors."

EDAMS_LINK="$(ls -1 /dev/edams/peripheral_* 2>/dev/null | head -1 || true)"
[ -n "${EDAMS_LINK}" ] || die "Symlink /dev/edams/peripheral_<serial> missing. Check /etc/udev/rules.d/99-edamperm.rules and /greengrass/peripheral_management/sanitize_serial."

log "OK - ${LP_NODE} created"
log "OK - ${EDAMS_LINK} -> $(readlink -f "${EDAMS_LINK}")"

# 8. Self-test (optional, prints a small ZPL label)
if [ "${1:-}" = "--test" ]; then
    log "Sending self-test label"
    printf '^XA^FO50,50^A0N,50,50^FDEDAMS OK^FS^XZ' > "${EDAMS_LINK}"
    log "Self-test sent. Check printer output."
fi

log "Done. EDAMS PrintServer should now print from ioprint."
